use crate::device::SystemInfo;
use anyhow::{Result, anyhow};
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

#[allow(dead_code)]
#[derive(Debug, Clone)]
pub struct ServiceConfig {
    pub unit_name: String,
    pub description: String,
    pub app_name: String,
    pub binary_name: String,
    pub source_binary_path: PathBuf,
    pub exec_start: String,
    pub working_dir: String,
    pub user: String,
    pub group: String,
    pub restart_policy: String,
    pub wanted_by: String,
    pub environment: String,
    pub extra_flags: String,
}

impl ServiceConfig {
    pub fn new(
        app_name: String,
        binary_name: String,
        source_binary_path: PathBuf,
        current_user: String,
    ) -> Self {
        let opt_dir = format!("/opt/{}", app_name);
        let opt_exec = format!("{}/{}", opt_dir, binary_name);
        let unit_name = format!("{}.service", app_name);
        let description = format!("{} Service generated by systemdfilegenerator", app_name);

        Self {
            unit_name,
            description,
            app_name,
            binary_name,
            source_binary_path,
            exec_start: opt_exec,
            working_dir: opt_dir,
            user: current_user.clone(),
            group: current_user,
            restart_policy: "always".to_string(),
            wanted_by: "multi-user.target".to_string(),
            environment: "".to_string(),
            extra_flags: "".to_string(),
        }
    }
}

pub fn render_service_file(config: &ServiceConfig, sys: &SystemInfo) -> String {
    let mut out = String::new();
    out.push_str("# ========================================================\n");
    out.push_str(&format!(
        "# Auto-generated Systemd Service File for {}\n",
        config.app_name
    ));
    out.push_str(&format!(
        "# Target System: {} ({}/{})\n",
        sys.hostname, sys.os_name, sys.cpu_arch
    ));
    out.push_str(&format!("# Target Path: {}\n", config.exec_start));
    out.push_str("# ========================================================\n\n");

    out.push_str("[Unit]\n");
    out.push_str(&format!("Description={}\n", config.description));
    out.push_str("After=network.target local-fs.target syslog.target\n\n");

    out.push_str("[Service]\n");
    out.push_str("Type=simple\n");

    let exec_cmd = if config.extra_flags.trim().is_empty() {
        config.exec_start.clone()
    } else {
        format!("{} {}", config.exec_start, config.extra_flags.trim())
    };

    out.push_str(&format!("ExecStart={}\n", exec_cmd));
    out.push_str(&format!("WorkingDirectory={}\n", config.working_dir));
    out.push_str(&format!("User={}\n", config.user));
    if !config.group.is_empty() {
        out.push_str(&format!("Group={}\n", config.group));
    }
    out.push_str(&format!("Restart={}\n", config.restart_policy));
    out.push_str("RestartSec=5s\n");

    if !config.environment.trim().is_empty() {
        for line in config.environment.lines() {
            let trimmed = line.trim();
            if !trimmed.is_empty() {
                out.push_str(&format!("Environment=\"{}\"\n", trimmed));
            }
        }
    }

    out.push_str("\n[Install]\n");
    out.push_str(&format!("WantedBy={}\n", config.wanted_by));

    out
}

pub fn save_service_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content)?;
    Ok(())
}

pub fn deploy_service_systemwide(config: &ServiceConfig, content: &str) -> Result<String> {
    let mut logs = String::new();

    // 1. Create target directory /opt/<app_name>
    let opt_dir = Path::new(&config.working_dir);
    logs.push_str(&format!("--> Creating directory: {}\n", opt_dir.display()));
    let status_mkdir = Command::new("sudo")
        .args(["mkdir", "-p", &config.working_dir])
        .status()?;

    if !status_mkdir.success() {
        return Err(anyhow!(
            "Failed to execute 'sudo mkdir -p {}'",
            config.working_dir
        ));
    }

    // 2. Copy binary to /opt/<app_name>/<binary_name>
    if config.source_binary_path.exists() {
        logs.push_str(&format!(
            "--> Copying binary {} -> {}\n",
            config.source_binary_path.display(),
            config.exec_start
        ));
        let status_cp = Command::new("sudo")
            .args([
                "cp",
                config.source_binary_path.to_str().unwrap(),
                &config.exec_start,
            ])
            .status()?;

        if !status_cp.success() {
            return Err(anyhow!("Failed to copy binary to {}", config.exec_start));
        }

        let status_chmod = Command::new("sudo")
            .args(["chmod", "+x", &config.exec_start])
            .status()?;
        if !status_chmod.success() {
            return Err(anyhow!(
                "Failed to set execute permissions on {}",
                config.exec_start
            ));
        }
    } else {
        logs.push_str(&format!(
            "--> Warning: Source binary file {} not found locally. Skipping binary copy.\n",
            config.source_binary_path.display()
        ));
    }

    // 3. Save service file to temporary path, then copy to /etc/systemd/system/
    let tmp_service_path = format!("/tmp/{}", config.unit_name);
    fs::write(&tmp_service_path, content)?;

    let target_service_path = format!("/etc/systemd/system/{}", config.unit_name);
    logs.push_str(&format!(
        "--> Deploying unit file to {}\n",
        target_service_path
    ));

    let status_service_cp = Command::new("sudo")
        .args(["cp", &tmp_service_path, &target_service_path])
        .status()?;

    if !status_service_cp.success() {
        return Err(anyhow!(
            "Failed to copy service file to {}",
            target_service_path
        ));
    }

    // 4. Reload systemd daemon
    logs.push_str("--> Reloading systemd daemon (sudo systemctl daemon-reload)...\n");
    let status_reload = Command::new("sudo")
        .args(["systemctl", "daemon-reload"])
        .status()?;

    if status_reload.success() {
        logs.push_str("--> systemd daemon reloaded successfully!\n");
    } else {
        logs.push_str("--> Note: Could not reload systemctl daemon automatically.\n");
    }

    logs.push_str(&format!("\nSUCCESS! Service deployed.\nTo start service, run:\n  sudo systemctl start {}\n  sudo systemctl status {}\n", config.unit_name, config.unit_name));

    Ok(logs)
}
